# Generated by Django 3.2.13 on 2023-05-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
