# Generated by Django 4.2 on 2023-06-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_questions_authon_sellectedquestions_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellectedquestions",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.questions",
            ),
        ),
    ]
