# Generated by Django 4.2 on 2023-06-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_sellectedquestions_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellectedquestions",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_set",
                to="questions.questions",
            ),
        ),
    ]
