# Generated by Django 4.2 on 2023-08-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_alter_sellectedquestions_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sellectedquestions",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_set",
                to="questions.questions",
            ),
        ),
    ]
