# Generated by Django 4.2 on 2023-08-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_alter_questions_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellectedquestions",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellectedQuestions_set",
                to="questions.questions",
            ),
        ),
    ]
